import Head from "next/head";
import Login from "@/components/Login"
import styles from "@/styles/Home.module.css"
import { useState, useEffect } from "react";
import Lista_Cursos from "./Lista_Cursos";
import { useDispatch, useSelector } from "react-redux";
import { resetState } from "@/redux/reducers/reducerUsuarios";

export default function Home() {

const [usuario,setUsuario]=useState(false)
//login de redux
const { login } = useSelector(state => state.usuariosState)
const { alumnos } = useSelector(state => state.usuariosState)
const dispatch= useDispatch()

  useEffect(() => {
  
    try {
      if(login){
        setUsuario(true)
      }      

    } catch (error) {
      console.log(error)
    }
  }, [usuario])

  function hanledReset(){
    dispatch(resetState())
  }

  return (
    <>
      <Head>
        <title>Centro de Estudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={ ` ${styles.contenedor}` } >
        {usuario ?  <Lista_Cursos />: <> <Login />
      {/*   <button onClick={hanledReset} >Resetear Alumnos</button> */}
        </>}

       <br/>
      
       
      </div>
      </>
  );
}
